Add extract CLI command
fedora-modularity/ModulemdTranslationHelpers pull request #2
Opened 2019-08-05 19:53 UTC by OrionStar25

2019-08-05 19:59 UTC, sgallagher requested changes
The `extract` command fails with:

```
Traceback (most recent call last):
  File "./ModulemdTranslationHelpers/cli.py", line 147, in <module>
    cli(obj={})
  File "/usr/lib/python3.7/site-packages/click/core.py", line 763, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 716, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1136, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 955, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 554, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./ModulemdTranslationHelpers/cli.py", line 99, in extract
    pofile.write_po(pot_file, catalog, sort_by_file=True)
  File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 552, in write_po
    for filename, lineno in sorted(message.locations):
ValueError: too many values to unpack (expected 2)

```

2019-08-05 19:59 UTC, sgallagher commented on ModulemdTranslationHelpers/cli.py
> +@click.option('--project-name', prompt='Project name',
Please don't prompt for this. If unspecified, it's better for it to just take the default.

2019-08-05 21:39 UTC, OrionStar25 commented
There still exists an error and I don't know what it means.

> Traceback (most recent call last):
  File "cli.py", line 148, in <module>
    cli(obj={})
  File "/usr/lib/python3.7/site-packages/click/core.py", line 721, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1065, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 894, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "cli.py", line 100, in extract
    pofile.write_po(pot_file, catalog, sort_by_file=True)
  File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 569, in write_po
    _write_message(message)
  File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 521, in _write_message
    _write('%smsgid %s\n' % (prefix, _normalize(message.id, prefix)))
  File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 482, in _normalize
    return normalize(key, prefix=prefix, width=width)
  File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 401, in normalize
    for line in string.splitlines(True):
AttributeError: 'NoneType' object has no attribute 'splitlines'

2019-08-06 11:33 UTC, sgallagher commented
> There still exists an error and I don't know what it means.
> 
> ```
> Traceback (most recent call last):
>   File "cli.py", line 148, in <module>
>     cli(obj={})
>   File "/usr/lib/python3.7/site-packages/click/core.py", line 721, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3.7/site-packages/click/core.py", line 1065, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3.7/site-packages/click/core.py", line 894, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "cli.py", line 100, in extract
>     pofile.write_po(pot_file, catalog, sort_by_file=True)
>   File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 569, in write_po
>     _write_message(message)
>   File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 521, in _write_message
>     _write('%smsgid %s\n' % (prefix, _normalize(message.id, prefix)))
>   File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 482, in _normalize
>     return normalize(key, prefix=prefix, width=width)
>   File "/usr/lib/python3.7/site-packages/babel/messages/pofile.py", line 401, in normalize
>     for line in string.splitlines(True):
> AttributeError: 'NoneType' object has no attribute 'splitlines'
> ```

That error means that you're trying to call a function `splitlines()` on a variable named `string` whose values is `None`. So something you passed in somewhere wasn't a real `string` but is `None` (Python's equivalent to `NULL`). So essentially this is a NULL-dereference and we need to figure out where you didn't create the correct string.

So let's look at the rest of the backtrace. This appears to be failing during a `_write()` to the pofile of a `msgid`, which we know is the source string. So you'll need to figure out which one is wrong (or if they all are).

My suggestion is to modify `cli()` so that when `debug == True`, you do `logging.setLevel(logging.DEBUG)` and then add some new `logging.debug()` calls around your code to print the strings you're processing and check whether any of them are coming up as `None`.

2019-08-15 16:52 UTC, OrionStar25 commented
```
[('nodejs;12;profile;default', 3), ('nodejs;12;profile;development', 3), ('nodejs;12;profile;minimal', 3), ('subversion;1.10;profile;common', 3), ('subversion;1.10;profile;server', 3)]
```

These are the locations where a `NULL` string was found. Now I am able to create a `.pot` file.

2019-08-15 16:59 UTC, sgallagher requested changes
The fact that those are `NULL` implies that you did the extraction incorrectly. If there was no source string for a profile description, you shouldn't be adding this location to the catalog.

2019-08-15 16:59 UTC, sgallagher commented on ModulemdTranslationHelpers/Utils.py
> +    if debug == True:
Don't add a `debug` parameter here, just have the `cli()` function set `logging.setLevel(logging.DEBUG)` globally. Then when you run with `--debug`, it'll be printed to the screen.

2019-08-15 16:59 UTC, sgallagher commented on ModulemdTranslationHelpers/tests/TestTranslationHelpers.py
> +            index, "fedora-modularity-translations", False)
This then becomes unnecessary.

2019-08-15 18:07 UTC, sgallagher requested changes
Almost there. Just a minor clean up of the debug stuff still.

The NULL handling looks correct.

2019-08-15 18:07 UTC, sgallagher commented on ModulemdTranslationHelpers/cli.py
> +    ctx.obj['debug'] = debug
Don't bother saving this to the `ctx.obj`. Just set the log level here.

2019-08-15 18:07 UTC, sgallagher commented on ModulemdTranslationHelpers/cli.py
> +    logger = logging.getLogger(__name__)
See above: move this into `cli()` so it will be active for any and all operations, not just `extract()`.

2019-08-16 13:49 UTC, sgallagher approved these changes
Looks good!

2019-08-16 13:50 UTC, merged